# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
      # This python version needs to be compatible with SCT, see setup.py
      python: "3.9"
  jobs:
    # NOTES:
    # - Add fix for mismatch between `batchgenerators` and `setuptools==78.0`
    # - We choose 75.8.2 to match the version installed in the conda 3.9 venv_sct
    # - This step *should* run after the environment is created, but before
    #   SCT+dependencies are installed (i.e. the `python: install:` config below)
    # - The reason we can't just pin this in `requirements.txt` is because
    #   RTD automatically upgrades `setuptools` beforehand. So we need to
    #   downgrade it after the environment is created + upgraded, but *before*
    #   installing everything in `requirements.txt`.
    #
    # FURTHER READING:
    #  - https://docs.readthedocs.com/platform/stable/builds.html#understanding-the-build-process
    #  - https://docs.readthedocs.com/platform/stable/build-customization.html#extend-or-override-the-build-process
    post_create_environment:
      - python -m pip install setuptools==75.8.2

python:
  install:
    - requirements: requirements.txt
    # Install SCT itself
    - path: .
      extra_requirements:
        - docs
# This file is just a duplicate of the .[docs] requirements specified
# in the previous point (see setup.py), so it's not necessary:
#    - requirements: documentation/source/requirements.txt

# The build happens in the documentation/source/ directory
sphinx:
  configuration: documentation/source/conf.py
  fail_on_warning: true
