function sct_get_centerline_auto_t2(fname,verbose)
% sct_get_centerline_auto_t2(fname)
dbstop if error
if nargin<2
    verbose=false;
end
[fname,path,ext]=sct_tool_remove_extension(fname,1);
nii=load_nii([fname ext]);
pos=sct_centerline_createRoi(nii.img);
v=double(nii.img);
[~,~,S]=sct_minimalPath3d(v(pos(1):pos(2),pos(3):pos(4),pos(5):pos(6)),sqrt(2),1,verbose);
S=int8(S); S(S==0)=inf; S=smooth3(S);
S2=inf*zeros(size(nii.img));
[~,~,S2(pos(1):pos(2),pos(3):pos(4),pos(5):pos(6))]=sct_minimalPath3d(S,1,0,verbose);
binaire2=false(size(S2));
N=floor(15*15/(nii.scales(1)*nii.scales(2)));
centerline=nan*zeros(size(nii.img,3),3);
for level=1:size(nii.img,3)
    k=v(:,:,level);
    u=S2(:,:,level);
    t=sort(u(:));
    BW=bwconvhull(u<=t(N));
    
    if verbose
        figure(3)
        imagesc(u<t(N)); drawnow
        figure(4)
        imagesc(k); drawnow
        imagesc(BW); drawnow
    end
    ctr=regionprops(BW,'Centroid');
    if ~isempty(ctr)
        centerline(level,:)=[round(ctr.Centroid(2)),round(ctr.Centroid(1)),level];
    end
end
x=centerline(:,1); y=centerline(:,2); z=[1:size(nii.img,3)]*nii.scales(3);
rm=isnan(x)|isnan(y);
[fitresult, gof] = createFit(z(~rm), x(~rm));
x=feval(fitresult,z);
[fitresult, gof] = createFit(z(~rm), y(~rm));
y=feval(fitresult,z);

for iz=1:size(nii.img,3)
    binaire2(max(round(x(iz)),1),max(round(y(iz)),1),iz)=true;
end
niibin=nii;
niibin.img=binaire2;
save_nii(niibin,[fname '_centerline' ext])
save_nii(nii,[fname '_orient' ext])


function [fitresult, gof] = createFit(x2, y2)
%CREATEFIT(X2,Y2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x2
%      Y Output: y2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Apr-2015 15:39:39


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x2, y2 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.0001;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y2 vs. x2', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'x2' );
% ylabel( 'y2' );
% grid on



