function sct_smoothhist(file,varargin)
% sct_smoothhist(nifti, ([xmin xmax]) )
data=read_avw(file);
data=data(:);
data(data==0)=[];
[n,xout] = hist(data,length(data)/10);
[fitresult, gof] = createFit(xout, n);

% plot smooth hist
n_smooth=feval(fitresult,xout);
figure, area(xout,n_smooth)
if ~isempty(varargin)
    xlim(varargin{1});
end

function [fitresult, gof] = createFit(xout, n)
%CREATEFIT(XOUT,N)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xout
%      Y Output: n
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Apr-2014 20:05:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xout, n );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( ft );
opts.SmoothingParam = 0.99;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'n vs. xout', 'nice histo', 'Location', 'NorthEast' );
% Label axes
xlabel( 'xout' );
ylabel( 'n' );
grid on


